#!/bin/sh

case $1 in
    start)
        echo "Starting modules"
        cd /lib/modules/6.1.44/extra/
        /usr/bin/scull_load
        /usr/bin/module_load faulty
        /usr/bin/aesdchar_load
        modprobe hello
        ;;
    stop)
        echo "Stopping modules"
        /usr/bin/scull_unload
        /usr/bin/module_unload faulty
        /usr/bin/aesdchar_unload
        rmmod hello
	    ;;
    *)
        exit 1
        ;;
esac

exit 0
