#!/bin/sh

case $1 in
    start)
        echo "Starting modules"
        /usr/bin/scull_load
        /usr/bin/module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Stopping modules"
        /usr/bin/scull_unload
        /usr/bin/module_unload faulty
        rmmod hello
	    ;;
    *)
        exit 1
        ;;
esac

exit 0
